module.exports = {
    SHIFT_TYPE: {
        DAY: 0,
        NIGHT: 1
    },
    MACHINE_TYPE_KEY_MAPPING: {
        "rapier": ["warp", "weft", "feeder", "manual", "other"],
        "airjet": ["h1", "h2", "warp", "other"],
        "waterjet": ["warp", "weft", "feeder", "manual", "other"],
        "circular": ["warp", "weft", "feeder", "manual", "other"]
    },
    RAPIER_DISPLAYS: ["nazon", "chitic", "pickwell"],
    AIRJET_DISPLAYS: ["biana"],
    DIRECT_DISPLAYS: ["haiwell", "picanolRapier", "picanolAirjet", "itema"],
    POWER_OFF_STOP_CODE: 9999,
    POWER_OFF_STOP_REASON: "Power Off",
    // Pickwell PRL50 LW5014-LW5019 bitfields. Empty string = reserved bit.
    PICKWELL_ALARM_BITS: {
        5014: [
            "Low oil pressure",
            "Jacquard machine failure",
            "Main motor overload",
            "Oil pump overheating",
            "Oil pump motor overload",
            "Oil temperature protection",
            "Fan overload",
            "Brake pad failure",
            "Main circuit closed",
            "Brake overheating",
            "Fan overheating",
            "Main motor temperature alarm",
            "Oil pressure is too high",
            "Loom synchronization failure",
            "Weaving position proximity switch is not lit",
            "Thermal cutter failure"
        ],
        5015: [
            "Tension protection proximity switch action",
            "ETU-ELO communication abnormality",
            "Electronic color selection communication abnormality",
            "Electronic selvedge communication abnormality",
            "Driver board communication abnormality",
            "ETU-ELO wrong parameter",
            "Take-up motor failure",
            "ETU-ELO motor 1 failure",
            "ETU-ELO motor 2 failure",
            "Motor failure of fabric winder",
            "Warp tension 1 is too small",
            "Warp tension 1 is too large",
            "Warp tension 2 is too small",
            "Warp tension 2 is too large",
            "The tension of the fabric winder is too small",
            "Excessive tension on fabric winder"
        ],
        5016: [
            "ETU-ELO encoder failure",
            "Tension out of tolerance",
            "Main motor emergency stop",
            "Main motor power off",
            "Speed feedback error",
            "IGBT undersaturation",
            "Driver board radiator overheating",
            "Main motor overcurrent",
            "Driver board overvoltage",
            "Driver board undervoltage",
            "Current zero error",
            "Driver board leakage fault",
            "Main motor position out of tolerance",
            "Reluctance motor overload",
            "Main off coil open circuit",
            "Reluctance motor drive board failure"
        ],
        5017: [
            "Weft proximity switch is not lit",
            "Weaving position proximity switch is always on",
            "Loom positioning timeout",
            "Spindle encoder failure",
            "Weft finding process interrupted",
            "The loom is in power-off protection",
            "Braking distance is too long",
            "Main motor response timeout",
            "Loom brake failure",
            "Waiting for parking angle timeout",
            "Weft finding failure, please check the oil supply system",
            "Loom startup failure",
            "The weaving position proximity switch does not light up during fast running",
            "Cam level approach fault",
            "FLASH memory read and write error",
            "Quick-sync error"
        ],
        5018: [
            "Loom speed is too low",
            "Loom speed is too high",
            "Encoder direction error",
            "Weft finding proximity switch is not extinguished",
            "",
            "Working parameter recovery failed",
            "The sequence of weaving approach and weft finding approach signals is wrong",
            "Check the wiring sequence of weft finding and pressurizing solenoid valves",
            "No servo action detected",
            "Servo unexpected action",
            "ETU-ELO board restarts",
            "ETU-ELO I2C error",
            "ETU-ELO Status Error",
            "Take-up motor overspeed",
            "Let-off 1 motor overspeed",
            "Let-off 2 motor overspeed"
        ],
        5019: [
            "",
            "",
            "",
            "",
            "The weft return axis angle is out of tolerance",
            "Dobby oil level low",
            "Multi-arm oil level sensor failure",
            "Main motor contactor abnormality",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ]
    }
};